{
 "title": "huz",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Release Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "rawSql": "select count(*) from release" }
   ]
  },
  {
   "title": "Track Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "rawSql": "select count(*) from track" }
   ]
  },
  {
   "title": "Album Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "rawSql": "select count(*) from album" }
   ]
  },
  {
   "title": "Artist Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "rawSql": "select count(*) from artist" }
   ]
  },
  {
   "title": "Release Count VS Update Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  tag AS metric,\n  count\nFROM releasestats\nWHERE\n  $__timeFilter(updated_at)\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  tag AS metric,\n  count\nFROM updatestats\nWHERE\n  $__timeFilter(updated_at)\nORDER BY 1,2"
    }
   ]
  }
 ]
}